import type { Metadata } from 'next';
import { LegalPage } from '@/components/section/LegalPage';

export const metadata: Metadata = {
  title: 'Privacy Policy | Aayulogic',
  description:
    'How Aayulogic collects, uses, stores, and protects personal information across our global operations.',
};

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy"
      highlight="Policy"
      subtitle="How we collect, use, and protect your information across all Aayulogic services and engagements."
      lastUpdated="May 2026"
      intro="Aayulogic Inc. (Canada) and Aayulogic Systems Pvt. Ltd. (Nepal) — together “Aayulogic”, “we”, “us” — respect your privacy. This policy explains what personal data we collect when you visit our websites, engage our services, or use our products, and how that data is handled under ISO 27001 controls and applicable data-protection law."
      sections={[
        {
          heading: 'Information we collect',
          body: [
            'We collect information you provide directly to us — for example when you fill in a contact form, request a proposal, apply for a role, or subscribe to updates — together with limited technical metadata generated by your interactions with our sites.',
          ],
          list: [
            'Identity & contact data: name, email, phone, organization, job title.',
            'Engagement context: project description, budget range, timeline, region.',
            'Technical data: IP address, device type, browser, pages visited, referring URL.',
            'Cookies & analytics identifiers (see our Cookie Policy for details).',
          ],
        },
        {
          heading: 'How we use your information',
          body: [
            'We process your data only for clearly defined business purposes and never sell it to third parties.',
          ],
          list: [
            'Respond to enquiries, scope engagements, and deliver contracted services.',
            'Operate, maintain, and secure our platforms, products, and infrastructure.',
            'Improve our services through aggregated analytics and feedback.',
            'Send relevant operational communications and, where permitted, marketing updates you can unsubscribe from at any time.',
            'Comply with legal obligations and protect the rights, safety, and property of Aayulogic and its clients.',
          ],
        },
        {
          heading: 'Legal bases for processing',
          body: [
            'Where GDPR or equivalent regimes apply, we rely on one or more of the following bases: your consent, the necessity of processing to perform a contract, our legitimate business interests, and compliance with legal obligations.',
          ],
        },
        {
          heading: 'Data sharing & subprocessors',
          body: [
            'We share data only with vetted subprocessors who are contractually bound to confidentiality and security standards equivalent to our own — including cloud hosting (AWS, Azure, GCP), CRM tooling, and analytics platforms. A current list is available on request.',
            'We may disclose information if required by law, regulation, court order, or to enforce our agreements.',
          ],
        },
        {
          heading: 'International transfers',
          body: [
            'Our delivery model is distributed across Canada, Nepal, the United States, Australia, and the UAE. Cross-border data transfers are governed by Standard Contractual Clauses (SCCs) or equivalent safeguards.',
          ],
        },
        {
          heading: 'Retention',
          body: [
            'We retain personal data only as long as necessary to fulfil the purposes set out in this policy or to comply with legal, accounting, or reporting requirements — and then delete or anonymize it under documented retention schedules.',
          ],
        },
        {
          heading: 'Your rights',
          body: [
            'Subject to applicable law, you have rights to access, correct, update, port, or delete the personal data we hold about you, and to object to or restrict certain processing.',
          ],
          list: [
            'Request access to a copy of your personal data.',
            'Request correction of inaccurate or incomplete data.',
            'Request deletion or restriction of processing.',
            'Object to direct marketing or to processing based on legitimate interests.',
            'Withdraw consent at any time, where consent is the basis of processing.',
          ],
        },
        {
          heading: 'Security',
          body: [
            'Aayulogic operates an ISO 27001-certified Information Security Management System. We apply layered controls — encryption at rest and in transit, least-privilege IAM, code review, monitoring, and incident-response procedures — to protect personal data from unauthorized access, disclosure, alteration, or destruction.',
          ],
        },
        {
          heading: 'Children',
          body: [
            'Our services are intended for businesses. We do not knowingly collect personal data from individuals under the age of 16. If you believe a child has provided us with personal data, contact us and we will delete it.',
          ],
        },
        {
          heading: 'Changes to this policy',
          body: [
            'We may update this policy from time to time. Material changes will be communicated through our website or directly where required. The “Effective” date at the top of this page reflects the latest revision.',
          ],
        },
      ]}
      contactEmail="privacy@aayulogic.com"
    />
  );
}
